language: python

cache:
  - pip
  - yarn

python:
  - "2.7.11"

node_js:
  - "6"

services:
  - postgresql
  - rabbitmq

sudo: false

install:
  - pip install -r requirements.txt -r test_requirements.txt
  - yarn global add eslint

before_script:
  - psql -c 'create database anyway;' -U postgres
  - export DATABASE_URL='postgresql://postgres@localhost/anyway'
  - ./main.py init_db
  - celery worker -A anyway.clusters_calculator -D

script:
  - pylint -j $(nproc) anyway tests
  - eslint static/js --ignore-path=static/js/.eslintignore
  - ./main.py process_data
  - ./main.py import_united_data --light
  - pytest tests
  - kill $(cat celeryd.pid)
  - ANYWAY_DISABLE_CELERY=1 pytest tests/test_flask.py::test_clusters
